---
title: "HW6_P1"
author: "Yuqi Tu and Xin Yin"
date: "November 14, 2017"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
editor_options: 
  chunk_output_type: console
---


```{r library, message=FALSE, warning=FALSE}
library(tidyverse)
library(tidytext)
library(rvest)
library(httr)
library(haven)
library(janitor)
library(rnoaa)
library(stringr)
library(forcats)
library(viridis)
library(plotly)
library(flexdashboard)
```



```{r read and load data, message= FALSE, warning= FALSE}
instacart = read_csv("./data_hw6/instacart_train_data.csv.zip") %>%
    clean_names()
```



```{r department donut chart analysis}
department_items_ordered = summarize(group_by(instacart, department),n=n()) %>% 
  arrange(desc(n)) %>% 
  rename(number_of_item_ordered = n)


```



```{r data analysis order hour for items from the household department}
household = 
  filter(instacart,department == "household") %>%
  select(department, order_hour_of_day) %>%
  arrange(order_hour_of_day)
```


```{r analysis c}
aisle_tidy =
  instacart %>%
  select(aisle, order_hour_of_day) %>%
  group_by(aisle, order_hour_of_day) %>%
  summarize(n = n()) %>%
  ungroup()
```








Row
-----------------------------------------------------------------------

### Chart A

```{r department donut chart plot }
donut_chart = department_items_ordered %>% 
  mutate(text_label = str_c("Number of Items Ordered:", number_of_item_ordered)) %>%
  plot_ly(labels = ~department, values = ~number_of_item_ordered) %>% 
  add_pie(hole = 0.4) %>% 
  layout(title = "The Number of Items Ordered within Each Department", showlegend = T,
         xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE), 
         yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))
donut_chart

# In New York City, online grocery service is popular for people to shop online from local stores. Among 21 departments of food in grocery shops, produce (29.5%), dairy eggs(15.7%), snacks(8.58%), beverages(8.24%) and forzen (7.25%) departments have much more ordered items than other department, while bulk (0.13%), pets(0.32%), and alcohol(0.40%) department have much fewer ordered items. 


```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Chart B

```{r histogram plot }
#  the hour of the day on which the order was placed for household department
fit <- density(household$order_hour_of_day)
household_plot =
  household %>%
  plot_ly(x = ~order_hour_of_day, type = "histogram", name = "Frequency") %>%
  add_trace(x = fit$x, y = fit$y, type= "scatter", mode = "lines", fill = "tozeroy", yaxis = "y2", name = "Density") %>%
  layout(yaxis2 = list(overlaying = "y", side = "right")) %>%
  layout(title = "The Hour of the Day on which the Order was placed for Household Department",
         xaxis = list(title = "Order hour of the day"), 
         yaxis = list(title = "Frequency"))
household_plot
## We can see from the plot that every day before 9am, there are not many order placed from the household department but it's increasing. At around 9am, orders placed reach the maximum from the household department and then decreases for the rest of the day. 
```


### Chart C

```{r line graph about}
aisle_plot =
  aisle_tidy %>%
  plot_ly(x = ~order_hour_of_day, y = ~n, 
          split = ~aisle, type = 'scatter', mode = 'lines') %>%
  layout(title = "The Association of Order Hour and Frequency for Different Aisles",
         xaxis = list(title = "Order hour of day", zeroline = F),
         yaxis = list(title = "Frequency", zeroline = F))
aisle_plot
# This line graph shows the order hour of the day on which the order was placed, the number of times an item was ordered from a certain aisle at that particular hour and also the pattern of purchase time of different aisles. For all the aisles, they have the similar purchase pattern associated with time, which people ordered more during daytime. The top 3 aisles from which people ordered the most are fresh vegetables, fresh fruits, packaged vegetables. 
```



